spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  thymeleaf:  # 可以不设置
    cache: false  #关闭缓存
    prefix: classpath:/templates/
    suffix: .html
#      mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    
